export const lang =
    [
        {
            "field1": "",
            "field2": "1",
            "field3": "商店图",
            "Len": "20",
            "zh-CN": "《弓箭传说》团队最新力作！",
            "en": "‘Archero’ Team’s Newest Hit!",
            "zh-TW": "《弓箭傳說》團隊最新力作！",
            "ja": "『アーチャー伝説』チームの最新ヒット！",
            "ko": "‘궁수의 전설' 개발팀의 신규 히트작!"
        },
        {
            "field1": "",
            "field2": "2",
            "field3": "商店图",
            "Len": "20",
            "zh-CN": "首创Roguelite弹珠RPG",
            "en": "Innovative Roguelite RPG Block Breaker!",
            "zh-TW": "首創Roguelite彈珠RPG",
            "ja": "ローグライト、RPG、ブロック崩しを組み合わせた革新的なゲーム！",
            "ko": "최초 로그라이트 벽돌깨기 RPG!"
        },
        {
            "field1": "",
            "field2": "3",
            "field3": "商店图",
            "Len": "15",
            "zh-CN": "单指操作，轻松发射！",
            "en": "One finger control; shoot shoot shoot!",
            "zh-TW": "單指操作，輕鬆發射！",
            "ja": "指1本でコントロール：撃って撃って撃ちまくれ！",
            "ko": "한 손 조작! 쉽게 쏴라!"
        },
        {
            "field1": "",
            "field2": "4",
            "field3": "商店图",
            "Len": "15",
            "zh-CN": "超100种全新技能",
            "en": "More than 100 new skills!",
            "zh-TW": "超100種全新技能",
            "ja": "100種以上の新しいスキル！",
            "ko": "100가지 넘는 신규 스킬!"
        },
        {
            "field1": "",
            "field2": "5",
            "field3": "商店图",
            "Len": "15",
            "zh-CN": "超多Boss，怪物，章节",
            "en": "Plenty of Bosses, Monsters & Chapters!",
            "zh-TW": "超多Boss，怪物，章節",
            "ja": "たくさんのボス、モンスター、チャプター！",
            "ko": "수많은 보스, 몬스터와 챕터!"
        },
        {
            "field1": "",
            "field2": "6",
            "field3": "首图按钮",
            "Len": "10",
            "zh-CN": "预约好礼",
            "en": "Pre-Order Rewards",
            "zh-TW": "預約好禮",
            "ja": "プレオーダー報酬",
            "ko": "사전예약 보상"
        },
        {
            "field1": "",
            "field2": "7",
            "field3": "首图标题",
            "Len": "10",
            "zh-CN": "游戏特色",
            "en": "Special Features",
            "zh-TW": "遊戲特色",
            "ja": "特別な機能",
            "ko": "핀볼도사의 특징"
        },
        {
            "field1": "",
            "field2": "8",
            "field3": "首页浮窗",
            "Len": "10",
            "zh-CN": "奖励查询",
            "en": "Check Rewards",
            "zh-TW": "獎勵查詢",
            "ja": "報酬をチェック",
            "ko": "보상 확인하기"
        },
        {
            "field1": "",
            "field2": "9",
            "field3": "验证页面",
            "Len": "15",
            "zh-CN": "完成邮箱验证赢双份好礼！",
            "en": "<span style=\"font-size:1.4rem\">Verify your email to get the rewards!</span>",
            "zh-TW": "完成郵箱驗證贏雙份好禮！",
            "ja": "<span style=\"font-size:2rem\">メールを確認して報酬をゲットしよう！</span>",
            "ko": "<span style=\"font-size:2rem\">이메일 인증을 완료하여 보상을 두배로 받으세요!</span>"
        },
        {
            "field1": "",
            "field2": "10",
            "field3": "验证页面",
            "Len": "15",
            "zh-CN": "已预约人数：",
            "en": "Pre-Ordered Players:",
            "zh-TW": "已預約人數：",
            "ja": "事前に確保したプレイヤー：",
            "ko": "사전예약 플레이어:"
        },
        {
            "field1": "",
            "field2": "11",
            "field3": "验证页面",
            "Len": "10",
            "zh-CN": "请输入您的邮箱",
            "en": "Please enter your Email",
            "zh-TW": "請輸入您的郵箱",
            "ja": "メールアドレスを入力してください",
            "ko": "이메일 주소를 입력하세요"
        },
        {
            "field1": "",
            "field2": "12",
            "field3": "验证页面",
            "Len": "10",
            "zh-CN": "获取验证码",
            "en": "Send Verification Code",
            "zh-TW": "獲取驗證碼",
            "ja": "確認コードを送信",
            "ko": "인증 코드 받기"
        },
        {
            "field1": "",
            "field2": "13",
            "field3": "验证页面",
            "Len": "10",
            "zh-CN": "请输入您的验证码",
            "en": "Enter the Code",
            "zh-TW": "請輸入您的驗證碼",
            "ja": "確認コードを入力してください",
            "ko": "인증 코드를 입력하세요"
        },
        {
            "field1": "",
            "field2": "14",
            "field3": "验证页面",
            "Len": "10",
            "zh-CN": "领取奖励",
            "en": "Claim Rewards",
            "zh-TW": "領取獎勵",
            "ja": "報酬を受け取る",
            "ko": "보상 획득"
        },
        {
            "field1": "",
            "field2": "15",
            "field3": "验证邮箱失败",
            "Len": "10",
            "zh-CN": "验证码错误",
            "en": "Code error",
            "zh-TW": "驗證碼錯誤",
            "ja": "コードエラー",
            "ko": "인증 코드 오류"
        },
        {
            "field1": "",
            "field2": "16",
            "field3": "验证页面",
            "Len": "20",
            "zh-CN": "我同意使用个人邮箱接收游戏信息",
            "en": "I accept to receive updates of the game",
            "zh-TW": "我同意使用個人郵箱接收遊戲信息",
            "ja": "ゲームのアップデートを受け取ることに同意します",
            "ko": "이메일로 게임 정보 수신에 동의합니다."
        },
        {
            "field1": "",
            "field2": "17",
            "field3": "领取成功界面",
            "Len": "10",
            "zh-CN": "恭喜您预约成功",
            "en": "<span style=\"font-size:2rem\">Congrats on your Pre-Order!</span>",
            "zh-TW": "恭喜您預約成功",
            "ja": "<span style=\"font-size:2rem\">正常に先行注文が行われました！</span>",
            "ko": "<span style=\"font-size:3rem\">사전예약을축하합니다!</span>"
        },
        {
            "field1": "",
            "field2": "19",
            "field3": "领取成功界面",
            "Len": "5",
            "zh-CN": "兑换码",
            "en": "Redeem Code",
            "zh-TW": "兌換碼",
            "ja": "コードを交換",
            "ko": "코드 사용"
        },
        {
            "field1": "",
            "field2": "20",
            "field3": "领取成功界面",
            "Len": "5",
            "zh-CN": "复制",
            "en": "Copy",
            "zh-TW": "複製",
            "ja": "コピー",
            "ko": "복사"
        },
        {
            "field1": "",
            "field2": "21",
            "field3": "领取成功界面",
            "Len": "5",
            "zh-CN": "即刻兑换",
            "en": "Redeem",
            "zh-TW": "即刻兌換",
            "ja": "交換",
            "ko": "사용"
        },
        {
            "field1": "",
            "field2": "22",
            "field3": "领取成功界面",
            "Len": "40",
            "zh-CN": "即刻点击下方按钮预约，公测当日即可使用礼包码，请妥善保存。",
            "en": "Tap the button below to Pre-Order! The code will be active once the game goes online, so keep your code safe!",
            "zh-TW": "即刻點擊下方按鈕預約，公測當日即可使用禮包碼，請妥善保存。",
            "ja": "下のボタンをタップして先行注文しよう！ゲームがオンラインになるとコードが有効になります。コードを安全に保管しておいてください！",
            "ko": "지금 바로 아래 버튼을 눌러 예약하세요! 기프트코드는 게임이 출시되면 사용할 수 있으니 꼭 저장해두세요!"
        },
        {
            "field1": "",
            "field2": "23",
            "field3": "FB按钮",
            "Len": "",
            "zh-CN": "粉丝页",
            "en": "Fan Page",
            "zh-TW": "粉絲頁",
            "ja": "ファンページ",
            "ko": "팬 페이지"
        },
        {
            "field1": "",
            "field2": "24",
            "field3": "错误提示",
            "Len": "",
            "zh-CN": "请同意勾选",
            "en": "Please Check the Box to Continue",
            "zh-TW": "請同意勾選",
            "ja": "同意してください",
            "ko": "동의해주세요"
        },
        {
            "field1": "",
            "field2": "25",
            "field3": "首页底部文案",
            "Len": "",
            "zh-CN": "",
            "en": "※本遊戲依遊戲軟體分級管理辦法分類為：「 普遍級 」<br/>\n適度消費<br/>\n※請注意使用時間，避免沉迷於遊戲<br/>\n※本遊戲為免費遊戲，但遊戲內另提供購買虛擬遊戲幣、物品等付費服務，請依個人興趣及能力進行<br/>\n關於訂閱<br/>\n※ 消費者為限制行為能力人者，本契約訂定時，應經消費者之法定代理人同意，本契約始生效力；消費者為無行為能力人者，本契約之訂定，應由消費者之法定代理人代為之，並應於消費者之法定代理人閱讀、瞭解並同意本契約之所有內容後，方得使用本遊戲服務，本契約條款變更時亦同",
            "zh-TW": "",
            "ja": "",
            "ko": ""
        },
        {
            "field1": "",
            "field2": "26",
            "field3": "邮件标题",
            "Len": "",
            "zh-CN": "【酷喵跑酷】請查收您的驗證碼",
            "en": "【Kinja Run】Please check your verification code",
            "zh-TW": "【【酷喵跑酷】請查收您的驗證碼",
            "ja": "【キンジャRUN】確認コードをご確認ください",
            "ko": "【닌자캣런】인증번호를 확인해주세요 "
        },
        {
            "field1": "",
            "field2": "27",
            "field3": "邮件正文",
            "Len": "",
            "zh-CN": "【酷喵跑酷】您的驗證碼是：XXXX，此驗證碼1小時內有效",
            "en": "【Kinja Run】Your verification code is: XXXX, this verification code is valid for 1 hour",
            "zh-TW": "【酷喵跑酷】您的驗證碼是：XXXX，此驗證碼1小時內有效",
            "ja": "【キンジャRUN】確認コードはXXXX、この確認コードは1時間以内に有効です",
            "ko": "【닌자캣런】인증 코드: XXXX, 이 인증 코드는 1시간 이내에 유효합니다."
        },
        {
            "field1": "",
            "field2": "28",
            "field3": "邮件格式错误提示",
            "Len": "",
            "zh-CN": "邮件格式错误",
            "en": "Wrong Email Format",
            "zh-TW": "郵件格式錯誤",
            "ja": "間違ったメールフォーマット",
            "ko": "잘못된 이메일 형식"
        },
        {
            "field1": "",
            "field2": "29",
            "field3": "奖励已领取",
            "Len": "",
            "zh-CN": "奖励已领取",
            "en": "Reward has been Collected",
            "zh-TW": "獎勵已領取",
            "ja": "報酬が集められました",
            "ko": "보상이 수집되었습니다"
        },
        {
            "field1": "30",
            "field2": "错误提示",
            "Len": "",
            "zh-CN": "活动已结束",
            "en": "The Event is Closed.",
            "zh-TW": "活動已結束",
            "ja": "イベントは終了しました",
            "ko": "이벤트가 종료되었습니다"
        },
        {
            "field1": "31",
            "field2": "邮件标题1",
            "Len": "",
            "zh-CN": "超多开服奖励等你来拿！",
            "en": "Plenty of free rewards await you! Login now and claim them!",
            "zh-TW": "超多免費獎勵，登錄即可領！",
            "ja": "無料報酬が盛りだくさん！今すぐログインして受け取ろう！",
            "ko": "지금 바로 로그인하여 풍부한 무료 보상을 받으세요!"
        },
        {
            "field1": "32",
            "field2": "开服奖励",
            "Len": "100钻+2000金币",
            "zh-CN": "",
            "en": "",
            "zh-TW": "",
            "ja": "",
            "ko": ""
        },
        {
            "field1": "33",
            "field2": "邮件标题2",
            "Len": "",
            "zh-CN": "【酷喵跑酷】現已上線！",
            "en": "【Kinja Run】 is getting ready to meet you all!",
            "zh-TW": "【酷喵跑酷】現已上線！",
            "ja": "【キンジャRUN】が正式リリースされました！",
            "ko": "핀볼도사를 곧 만나보실 수 있어요!"
        },
        {
            "field1": "34",
            "field2": "Social Media标题",
            "Len": "",
            "zh-CN": "关注我们的最新消息吧！",
            "en": "Follow us for recent news!",
            "zh-TW": "關注我們的最新消息吧！",
            "ja": "ゲームのSNSをフォローして最新ニュースをチェックしよう！",
            "ko": "팔로우하여 최신 소식을 놓치지마세요!"
        },
        {
            "field1": "35",
            "field2": "礼包码过期",
            "Len": "",
            "zh-CN": "礼包码已过期",
            "en": "Redeem code is expired",
            "zh-TW": "兌換碼已過期",
            "ja": "利用コードの有効期限が切れています",
            "ko": "사용 코드가 만료되었습니다."
        },
        {
            "field1": "36",
            "field2": "礼包码未生效",
            "Len": "",
            "zh-CN": "礼包码未生效，请稍后尝试",
            "en": "Redeem code is not activated, please try it later.",
            "zh-TW": "兌換碼未生效，請稍後嘗試",
            "ja": "利用コードが有効化されていません。しばらくしてからお試しください。",
            "ko": "코드 사용이 활성화되지 않았습니다. 나중에 시도하십시오."
        }
    ]
